### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by emcek** [AtomLinter/linter-erlc#6] opened 2015-07-13 10:46 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (C:\Users\gtqk84\.atom\packages\linter\lib\main.coffee:57:8)
Package.activateNow (C:\Users\gtqk84\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
<unknown> (C:\Users\gtqk84\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30)
Package.measure (C:\Users\gtqk84\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15)
Package.activate (C:\Users\gtqk84\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:213:14)
PackageManager.activatePackage (C:\Users\gtqk84\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21)
```

**Comment by Arcanemagus** [comment] 2016-01-14 17:39
Marking as a duplicate of #3.

**Closed by Arcanemagus** 2016-01-14 17:39 UTC
